# build.yaml
name: "Build"

on:
  push:
    branches:
      - main
    paths:
      - "**.user.js"
  workflow_dispatch:

jobs:
  build-alook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build Alook Extension
        run: python parse-to-alook.py
        shell: bash

      - name: Build Public Folder
        run: cp *.user.js public/ && cp *.alook public/ && cp -r demos public/
        shell: bash

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
